from .embedded_javascript_into_pdf import embedded_javascript_into_pdf
from .js_obfuscator import obfuscated_code
from .check_open_action import check_open_action
from .deploy_pdf import create_ssh_client, transfer_file, execute_powershell_script
from .fetch_alerts import fetch_alerts
from .analyse_alerts import analyze_alerts
from .virusshare_analysis import compute_file_hash, check_virusshare, analyze_virusshare_results